### ISSUE TITLE
Why disable host_key_checking?

### ISSUE THREAD

**Issue by ThisIsMissEm** [tomoconnor/parallax#1]
This seems like it'd have some potentially bad security implications, can you expand on why you've disabled it? Is it due to the nature of AWS / Cloud type environments?

**Comment by tomoconnor** [comment]
Mostly, because of the following reasons:
1) I've mostly been using this playbook inside controlled environments.
2) Pretty much everyone I know doesn't bother reading the host key thing, just says yes, blindly.

Feel free to disable it in your environment if you like.  There's worse sins in this code (check roles/common/files/insecure_sudoers).  Again, controlled environments over ease of deployment.
